sudo: required

language: python

env:
  - TEST_TARGET="other.test_a* other.test_b* other.test_c* other.test_d* other.test_e* other.test_f* other.test_g* other.test_h*"
  - TEST_TARGET="other.test_i* other.test_j* other.test_k* other.test_l* other.test_m* other.test_n* other.test_o* other.test_p* other.test_q* other.test_r* other.test_s* other.test_t* other.test_u* other.test_v* other.test_w* other.test_x* other.test_y* other.test_z* other.test_A* other.test_B* other.test_C* other.test_D* other.test_E* other.test_F* other.test_G* other.test_H* other.test_I* other.test_J* other.test_K* other.test_L* other.test_M* other.test_N* other.test_O* other.test_P* other.test_Q* other.test_R* other.test_S* other.test_T* other.test_U* other.test_V* other.test_W* other.test_X* other.test_Y* other.test_Z*"
  - TEST_TARGET=browser
  - TEST_TARGET="asm*.test_a* asm*.test_b*"
  - TEST_TARGET=asm*.test_c*
  - TEST_TARGET="default.test_d* asm1.test_d* asm2.test_d* asm2f.test_d* asm2g.test_d* asm3.test_d*"
  - TEST_TARGET=asm*.test_e*
  - TEST_TARGET=asm*.test_f*
  - TEST_TARGET="asm*.test_g* asm*.test_h* asm*.test_i* asm*.test_t*"
  - TEST_TARGET="asm*.test_j* asm*.test_k* asm*.test_l* asm*.test_m* asm*.test_n* asm*.test_o*"
  - TEST_TARGET="default.test_p* asm1.test_p* asm2.test_p* asm2f.test_p* asm2g.test_p* asm3.test_p*"
  - TEST_TARGET="asm*.test_q* asm*.test_r* asm*.test_s*"
  - TEST_TARGET="asm*.test_u* asm*.test_v* asm*.test_w* asm*.test_x* asm*.test_y* asm*.test_z*"

services:
  - docker

before_install:
  - docker pull ubuntu:16.04

install:
  - pip install flake8==3.4.1

script:
  - set -o errexit
  - flake8
  - echo $TEST_TARGET
  - docker build --build-arg TEST_TARGET="$TEST_TARGET" .

notifications:
  email: false
