/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mti_primitives_devices_FileOutputDevice */

#ifndef _Included_com_mti_primitives_devices_FileOutputDevice
#define _Included_com_mti_primitives_devices_FileOutputDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mti_primitives_devices_FileOutputDevice
 * Method:    PlatformOpen
 * Signature: (Ljava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_FileOutputDevice_PlatformOpen
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_mti_primitives_devices_FileOutputDevice
 * Method:    PlatformClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_FileOutputDevice_PlatformClose
  (JNIEnv *, jobject);

/*
 * Class:     com_mti_primitives_devices_FileOutputDevice
 * Method:    PlatformPresentAudio
 * Signature: ([BJJ)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_FileOutputDevice_PlatformPresentAudio
  (JNIEnv *, jobject, jbyteArray, jlong, jlong);

/*
 * Class:     com_mti_primitives_devices_FileOutputDevice
 * Method:    PlatformPresentVideo
 * Signature: ([BJJ)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_FileOutputDevice_PlatformPresentVideo
  (JNIEnv *, jobject, jbyteArray, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
