/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mti_primitives_devices_AudioInputDevice */

#ifndef _Included_com_mti_primitives_devices_AudioInputDevice
#define _Included_com_mti_primitives_devices_AudioInputDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mti_primitives_devices_AudioInputDevice
 * Method:    PlatformOpen
 * Signature: (Lcom/mti/primitives/devices/AudioMediaFormat;)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_AudioInputDevice_PlatformOpen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mti_primitives_devices_AudioInputDevice
 * Method:    PlatformGetDevices
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_AudioInputDevice_PlatformGetDevices
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mti_primitives_devices_AudioInputDevice
 * Method:    PlatformClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_AudioInputDevice_PlatformClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
