/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mti_primitives_devices_AudioOutputDevice */

#ifndef _Included_com_mti_primitives_devices_AudioOutputDevice
#define _Included_com_mti_primitives_devices_AudioOutputDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mti_primitives_devices_AudioOutputDevice
 * Method:    PlatformOpen
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_AudioOutputDevice_PlatformOpen
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_mti_primitives_devices_AudioOutputDevice
 * Method:    PlatformClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_AudioOutputDevice_PlatformClose
  (JNIEnv *, jobject);

/*
 * Class:     com_mti_primitives_devices_AudioOutputDevice
 * Method:    PlatformGetDevices
 * Signature: ([Lcom/mti/primitives/devices/AudioOutputDevice;)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_AudioOutputDevice_PlatformGetDevices
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_mti_primitives_devices_AudioOutputDevice
 * Method:    PlatformPresent
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_AudioOutputDevice_PlatformPresent
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
