/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mti_primitives_devices_VideoOutputDevice */

#ifndef _Included_com_mti_primitives_devices_VideoOutputDevice
#define _Included_com_mti_primitives_devices_VideoOutputDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mti_primitives_devices_VideoOutputDevice
 * Method:    PlatformPresent
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_VideoOutputDevice_PlatformPresent
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_mti_primitives_devices_VideoOutputDevice
 * Method:    PlatformGetDevices
 * Signature: ([Lcom/mti/primitives/devices/VideoOutputDevice;)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_VideoOutputDevice_PlatformGetDevices
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_mti_primitives_devices_VideoOutputDevice
 * Method:    PlatformOpen
 * Signature: (IIIIIJIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_VideoOutputDevice_PlatformOpen
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jlong, jint, jint, jboolean);

/*
 * Class:     com_mti_primitives_devices_VideoOutputDevice
 * Method:    PlatformClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mti_primitives_devices_VideoOutputDevice_PlatformClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
